### ISSUE TITLE
Modify Email Template Header and Footer to have CR Connect instead of Research Ramp-Up...

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#215]

**Comment by calexh-sar** [comment]
@cullerton CR Connect is in header and footer now, but instead of having CR Connect centered in the header...

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/90a39701-71eb-48fe-8b7b-82ed7e39528a)

...please left justify it so it is similar to the header in the app:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/0811e709-7fa9-4728-b891-0c8cd64eca42)

**Comment by cullerton** [comment]
@calexh-sar If you only knew how much time I spent trying to center it... 

Did I mention how much I love CSS ;)

**Comment by calexh-sar** [comment]
Working as designed.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8dfd0709-5ee9-497f-a066-aeabc4dbf3f8)
