### ISSUE TITLE
Timer Event Not Firing

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#346]
In the department_chair_approval workflow the time event attached to the Review Approval Request User Activity is configured like this...

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/65a05206-c133-4097-bb92-d53b68f71fba)

...but does not fire after 30 seconds (the real duration once this is in production will be 7 days).

In a Slack discussion with Kelly, he mentioned:
```
it looks like it needs a self.workflow.refresh_waiting_tasks()
in the bpmn runner
the test is NITimerDurationBoundaryTest.py
and the .2 seconds is just so it doesn't take forever
```
Dan mentioned in a post scrum discussion something similar, that we need to kick off a process that checks for when the duration has been met and execute the activity associated with it.

**Comment by w4kpm** [comment]
We talked about having:

1) something that looks at the workflow and determining if it is in status of waiting (This should already be happening - but I need to determine if this is really the case)
2) We need a process (flask cron??) that will look at all waiting tasks and run the workflow.refresh_waiting_tasks()
on it so that timed events happen

**Comment by w4kpm** [comment]
Verified the 'waiting' status of the workflow, but we need a better UI for this:

![image.png](https://images.zenhubusercontent.com/5f07192743a6e34ae3082f25/4e403696-127f-41dd-a957-0a79da595dd6)

**Comment by calexh-sar** [comment]
@danfunk I ran the Dept Chair workflow again and the reminder email hanging off the timer event was not sent.

**Comment by calexh-sar** [comment]
Working as designed
