### ISSUE TITLE
IND workflow value_expression not working

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#422]
Update: this is not limited to the IND workflow, see ticket #448

In the IND workflow the `IND2_HolderType` and `IND3_HolderType` Form Fields in the _Confirm IND Status User Task_ have `value_expression` Properties of `IND2_Holder_Type_Default` and `IND3_Holder_Type_Default`, respectively.  Each Form Field has the following enum Values:
 ![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/4f5d4651-c834-47dc-934e-d7b79f92a2b3)
and
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/1a147088-bb40-413f-b321-bfd6bdd62e4f)

When the Form initializes, it returns the following in task data: `"IND2_Holder_Type_Default": "NA"` and `"IND3_Holder_Type_Default": "NA"`,  but the fields show as Null:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/08100e99-7a2d-410d-8968-aa0878c1de00)
and
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/2773b4d1-88b3-4e62-b586-5f2e9d28f689)
instead of NA.

**Comment by calexh-sar** [comment]
Just found out a value_expression in the Study Information workflow is also not working, so not just isolated to IND workflow.

**Comment by danfunk** [comment]
@calexh-sar - The value_expression is working correctly.
The issue here, is the same problem we have had a hundred times now with drop down lists.  Drop down lists need to have both a label and value, rather than functioning like all other inputs.  We have dozens of special cases in the code now to handle this, and they just keep coming and coming.  We need to strongly consider removing these special cases, and allow dropdowns to function like all other inputs. 

If you want to set a default value on a dropdown, you can't just set the value.  You have to set both the value and the label as a dictionary. 

So the default value here would need to be:

 {'value': 'N/A', 'label': '....'}

**Comment by calexh-sar** [comment]
Working as designed.
