### ISSUE TITLE
Timer events should be current browser time zone not UTC based

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#425]
When entering a timer event that requires specifying a date and time, the event is currently based on UTC time.  We need to adjust this based on Easter Time.  At a later time we can do the additional work of automatically adjust to the time zone the Configurator is working in and/or having it as a preference setting.

**Comment by w4kpm** [comment]
Added a new library that should allow us to do the right thing. It **will not** automatically reason about where the user is, but will easily allow the user to add a timezone to the expected time.

Use it like so :

dateparser.parse('September 10 2021 at 10:05am EDT')

Also, previously we had problems with using now()-timedelta(minutes=10) directly in the time definition in a time event, because each time it would happily re-evaluate it and always kick it down the road. 

Instead you can now do a dateparser.parse('in 10 minutes')

please see dateparser https://dateparser.readthedocs.io/en/latest/ docs for a full explanation

**Comment by calexh-sar** [comment]
Not sure if I tested this correctly, but I configured an Intermediate Timer Event like

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/4e9393ec-c56a-4264-8d49-4e82993e2846)

in the dateparser_test workflow in Alex's Test and started it at 9:35pm.  Instead of pausing, the workflow executed immediately, as seen here:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/24c35d4c-1a28-45ed-9286-1094b16d7937)

Not sure if dateparser is not working or if this is an incorrect use of the Timer Definition type Date .

**Comment by calexh-sar** [comment]
I ran a second test with the following configuration:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/287b742b-fe4a-4135-b88e-edfd83a51f78)

which returned the following:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a41f7e11-d751-40b4-af61-e787482af6a5)

From this I suspect that the Date Time Definition does not honor time and the dateparser does recognize the timezone passed in (I should have used EST instead of EDT), but this is still a problem unless there is a way to programmatically change the timezone in the parameter.

**Comment by cullerton** [comment]
@calexh-sar can you try something like

`parse('January 12, 2012 10:00 PM', settings={'TIMEZONE': 'US/Eastern'})`

**Comment by calexh-sar** [comment]
Thanks, will do.  Pulling this ticket back for more testing a determination what, if anything needs to be done.

**Comment by danfunk** [comment]
nice.  Would be good to raise an error quickly - require a timezone
perhaps, just to avoid people having issues in the future.
