### ISSUE TITLE
Error validating workflow which use Library workflow Set Sponsor 

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#447]
When attempting to validate the Study Information workflow, I receive the different errors shown below.  These all may be related to the issue raised in Ticket #447, but adding this ticket in case some/all of these are different.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/3b034134-30fc-4a55-932e-aacc6ca9432b)

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c4ca7359-5094-4ff8-9e8f-450a7954a9b4)

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/711ed69d-706e-4d41-891b-cc3c2f7e4415)

**Comment by danfunk** [comment]
dc_ldap is undefined error was because this variable wasn't defined if a DC did not exist.  Modifying the script in Load Department Chair corrected this issue.

The "You specified an enumartion field (EntityName) with no options, was occuring because we didn't handle the case of an empty list of sponsors.  Modifying the script to check for an empty list of sponsors fixed this.

I've corrected both scripts and validation now passes.

**Comment by calexh-sar** [comment]
Closing per discussion with Dan.
