### ISSUE TITLE
LDAP Computing ID Lookup Script

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#53]
For cases when the Computing ID is not an input field and the LDAP information associated with it is needed, create a script which allows for one or more Computing IDs to be passed to it, as a variable or literally, which results in the default LDAP information associated with that Computing ID being added to the data variables.

**Comment by calexh-sar** [comment]
The initial need for this came from the RRT Approval decision table, where we were passing the Computing IDs for the approvers to the Approval app.  The Computing IDs were all the Approval app needed since it handled the LDAP lookup there.  But the RRP app wanted to show the PI who the Approver/ was/were.  Without this script, those names were entered into the decision table.

**Comment by danfunk** [comment]
Please make the following modifications

- [x] Rename the Script task "LdapReplace"
- [x] Update the task.data by replacing the given location in the task-data with the ldap information.
 For example, given that the task.data is
```
{ "supervisor": "dhf8r" }
```
calling  "#! LdapReplace supervisor"
should update the task data to now be:
```
{ "supervisor": {
     uid: "dhf8r",
     display_name: "Dan Funk"
     ...
   }
}
```
- [x] Allow for multiple arguments - so that you can replace many sections of the task.data if requested.
- [x] Add a test that loads up a bpmn, updates the data, executes the task, and assures that the update is in the correct place.

**Comment by calexh-sar** [comment]
Done and documented on wiki.
