### ISSUE TITLE
Dynamic Default not working for enums

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#98]
From Slack chat with Aaron:
I don't think value_expression  will work now with the enums setting the value to an object. I'd need to modify those components to catch value_expression and set them in a custom handler.

**Comment by ajlouie** [comment]
Fixed by:
https://github.com/sartography/cr-connect-frontend/commit/c879719b64127e25cf9c910cc13e8d7e85d02bbf
https://github.com/sartography/cr-connect-frontend/commit/2bfab5e3b1d285ac7890fe283903904d06b5ecbc
https://github.com/sartography/cr-connect-frontend/commit/58b98ae0d1225fc07ae08a8f762088cdb138ee12

**Comment by calexh-sar** [comment]
Working as designed
